# Generated by Django 2.2.6 on 2019-10-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='dete_added',
            new_name='date_added',
        ),
    ]
